"""update_provider_column_to_enum

Revision ID: fade6b6b793b
Revises: 4b8b4a02dd68
Create Date: 2025-04-22 20:00:51.237355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fade6b6b793b'
down_revision: Union[str, None] = '4b8b4a02dd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_credential_id', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_timestamp', table_name='events')
    op.drop_index('ix_events_user_id', table_name='events')
    op.drop_index('ix_events_vm_id', table_name='events')
    op.drop_table('events')
    op.alter_column('vms', 'status',
               existing_type=postgresql.ENUM('CREATING', 'RUNNING', 'STOPPED', 'TERMINATED', 'FAILED', name='vmstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('vms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('vms', 'vm_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_vms_provider'), 'vms', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vms_provider'), table_name='vms')
    op.alter_column('vms', 'vm_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('vms', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('vms', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vms', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREATING', 'RUNNING', 'STOPPED', 'TERMINATED', 'FAILED', name='vmstatus'),
               existing_nullable=True)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credential_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name='events_credential_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='events_user_id_fkey'),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], name='events_vm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_index('ix_events_vm_id', 'events', ['vm_id'], unique=False)
    op.create_index('ix_events_user_id', 'events', ['user_id'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_credential_id', 'events', ['credential_id'], unique=False)
    # ### end Alembic commands ###
